kind: pipeline
name: default

steps:
  - name: initial_notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: >
        Repository: *{{repo.name}}*. Status: *Running*. Author: *{{build.author}}*. Build: *#{{build.number}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. Logs: {{build.link}}
    when:
      event: tag
      ref: refs/tags/*

  - name: publish
    image: node:12.14.0-alpine3.11
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm publish
    when:
      event: tag
      ref: refs/tags/*

  - name: build_status_notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: >
        {{#success build.status}}
        Repository: *{{repo.name}}*. Status: *Completed*. Author: *{{build.author}}*. Build: *#{{build.number}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. Logs: {{build.link}}
        {{else}}
        Repository: *{{repo.name}}*. Status: *Failed*. Author: *{{build.author}}*. Build: *#{{build.number}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. Logs: {{build.link}}
        {{/success}}
    when:
      event: tag
      status: [success, failure]
